"""
To generate data run this file and pass arguments to this file.
For e.g.
Num_Of-call_records_per_hour =10
percentage_prob_fraudulent_call =0.2
number_of_hours=2 

Syntax :

python generate_data.py 10 0.2 2

"""

import sys
from TelcoGenerationEngine import *
telcoGenerationEngine = TelcoGenerationEngine()
telcoGenerationEngine.GenerateData(str(sys.argv))

"""
output generated by script is in format of 

SystemIdentity,RecordType, SwitchNum,CallingIMSI,CalledIMSI,CalledNum,CallPeriod,ServiceType,DateTime

We can add and modfy other fields too..
"""